parameters:
#    just2_frontend.example.class: Just2\FrontendBundle\Example

services:
    just2_frontend.twig.extension.timeago:
      class: Just2\FrontendBundle\Twig\Extension\TimeAgoExtension
      tags:
          - { name: twig.extension }

    just2_frontend.twig.extension.test:
      class: Just2\FrontendBundle\Twig\Extension\DateSearchExtension
      tags:
          - { name: twig.extension }
      arguments:
          manager: "@doctrine.orm.entity_manager"
          container: "@service_container"

    just2_frontend.twig.extension.index:
      class: Just2\FrontendBundle\Twig\Extension\IndexExtension
      tags:
          - { name: twig.extension }
      arguments:
          manager: "@doctrine.orm.entity_manager"