## YAML Template.
user_view_show:
    pattern:  /{id}/view
    defaults: { _controller: Just2FrontendBundle:Member:show }
    
user_view_edit:
    pattern: /{id}/edit
    defaults: { _controller: Just2FrontendBundle:Member:edit }
    
user_view_update:
    pattern: /{id}/update
    defaults: { _controller: Just2FrontendBundle:Member:update }
    requirements:
        _method: GET
    
bid_create_for_user:
    pattern:  /bid/create
    defaults: { _controller: Just2FrontendBundle:Bid:bid }
    
bids_date:
    pattern:  /date/view/{id}
    defaults: { _controller: Just2FrontendBundle:User:adminDateBids }
    
bids_date_acepted:
    pattern:  /date/view/{id}/acepted
    defaults: { _controller: Just2FrontendBundle:User:adminDateBidsAcepted }
    
bids_date_rejectered:
    pattern:  /date/view/{id}/rejectered
    defaults: { _controller: Just2FrontendBundle:User:adminDateBidsRejectered }
